name: Build

on:
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # Installs deps and builds
    - run: npm install
    # Runs tests
    - run: MAINNET_PROVIDER_URL=${{ secrets.MAINNET_PROVIDER_URL }} npm test
    # Updates code coverage badge in readme
    - name: Upload coverage to Codecov
      run: npm run coverage -- -t ${{ secrets.CODECOV_TOKEN }}
