name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo Running on branch ${{ github.ref_name }}
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      # Installs deps and builds
      - run: MAINNET_PROVIDER_URL=${{ secrets.MAINNET_PROVIDER_URL }} POLYGON_PROVIDER_URL=${{ secrets.POLYGON_PROVIDER_URL }} GOERLI_PROVIDER_URL=${{ secrets.GOERLI_PROVIDER_URL }} MUMBAI_PROVIDER_URL=${{ secrets.MUMBAI_PROVIDER_URL }} GOERLI_OPTIMISM_PROVIDER_URL=${{ secrets.GOERLI_OPTIMISM_PROVIDER_URL }} FUJI_PROVIDER_URL=${{ secrets.FUJI_PROVIDER_URL }} npm install
      # Runs tests
      - run: MAINNET_PROVIDER_URL=${{ secrets.MAINNET_PROVIDER_URL }} npm run test_coverage
      # Updates code coverage badge in readme
      - name: Upload coverage to Codecov
        run: npm run coverage -- -t ${{ secrets.CODECOV_TOKEN }}
